-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS PUBLIC."Customers" (
	"CustomerID" INTEGER NOT NULL,
	"CustomerName" CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT "pk_Customers" PRIMARY KEY ("CustomerID")
);

CREATE TABLE IF NOT EXISTS PUBLIC."CreditCards" (
	"CreditCardNumber" CHARACTER VARYING(20) NOT NULL,
	"CustomerID" INTEGER NOT NULL,
	CONSTRAINT "pk_CreditCards" PRIMARY KEY ("CreditCardNumber")
);

CREATE TABLE IF NOT EXISTS PUBLIC."MerchantCategories" (
	"MerchantCategoryID" SERIAL NOT NULL,
	"CategoryName" CHARACTER VARYING(20) NOT NULL CHECK (CHAR_LENGTH("CategoryName") > 0),
	CONSTRAINT "pk_MerchantCategories" PRIMARY KEY ("MerchantCategoryID")
);

CREATE TABLE IF NOT EXISTS PUBLIC."Merchants" (
	"MerchantID" SERIAL NOT NULL,
	"MerchantName" CHARACTER VARYING(100) NOT NULL CHECK (CHAR_LENGTH("MerchantName") > 0),
	"MerchantCategoryID" INTEGER,
	CONSTRAINT "pk_Merchants" PRIMARY KEY ("MerchantID")
);

CREATE TABLE IF NOT EXISTS PUBLIC."Transactions" (
	"TransactionID" INTEGER NOT NULL,
	"TransactionDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	"Amount" DOUBLE PRECISION NOT NULL CHECK ("Amount" > 0),
	"CreditCardNumber" CHARACTER VARYING(20),
	"MerchantID" INTEGER,
	CONSTRAINT "pk_Transactions" PRIMARY KEY ("TransactionID")
);

CREATE TABLE IF NOT EXISTS "TransactionLogs" (
	"LogID" SERIAL PRIMARY KEY,
	"TransactionID" INT NOT NULL,
	"TransactionDate" TIMESTAMP NOT NULL,
	"Amount" DOUBLE PRECISION NOT NULL,
	"CreditCardNumber" VARCHAR(20) NOT NULL,
	"MerchantID" INT NOT NULL,
	"DeletedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ArchivedTransactions" (
	"TransactionID" INT PRIMARY KEY,
	"TransactionDate" TIMESTAMP NOT NULL,
	"Amount" DOUBLE PRECISION NOT NULL,
	"CreditCardNumber" VARCHAR(20) NOT NULL,
	"MerchantID" INT NOT NULL,
	"ArchivedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Merchants"
ADD COLUMN "TransactionCount" INT DEFAULT 0;

ALTER TABLE IF EXISTS PUBLIC."CreditCards"
ADD CONSTRAINT "fk_CreditCards_CustomerID" FOREIGN KEY ("CustomerID") REFERENCES PUBLIC."Customers" ("CustomerID") MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;

ALTER TABLE IF EXISTS PUBLIC."Merchants"
ADD CONSTRAINT "fk_Merchants_MerchantCategoryID" FOREIGN KEY ("MerchantCategoryID") REFERENCES PUBLIC."MerchantCategories" ("MerchantCategoryID") MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;

ALTER TABLE IF EXISTS PUBLIC."Transactions"
ADD CONSTRAINT "fk_Transactions_CreditCardNumber" FOREIGN KEY ("CreditCardNumber") REFERENCES PUBLIC."CreditCards" ("CreditCardNumber") MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE IF EXISTS PUBLIC."Transactions"
ADD CONSTRAINT "fk_Transactions_MerchantID" FOREIGN KEY ("MerchantID") REFERENCES PUBLIC."Merchants" ("MerchantID") MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;

END;